# https://docs.gradle.org/current/userguide/platforms.html#sec:importing-catalog-from-file 참고
[versions]
# Config
androidCompileSdkVersion = "33"
androidMinSdkVersion = "21"
androidTargetSdkVersions = "33"

androidxCore = "1.9.0"
androidxCompat = "1.6.0"
androidxCompose = "1.3.2"
androidxComposeMaterial = "1.3.1"
androidxComposeFoundation = "1.3.1"
androidxActivityCompose = "1.6.1"
okhttp = "4.10.0"
retrofit = "2.9.0"
kotlinxSerializationJson = "1.4.1"
retrofitKotlinxSerializationJson = "0.8.0"
kotlin = "1.7.20"
androidGradlePlugin = "7.3.1"
material = "1.8.0"
constraintLayout = "2.1.4"
daggerHilt = "2.44.2"
hiltNavigationCompose = "1.0.0"
timber = "5.0.1"
androidxConstraintlayoutCompose = "1.0.1"
androidxPagingCompose = "1.0.0-alpha17"
androidxLifecycleViewmodel = "2.5.1"
androidxNavigationCompose = "2.5.3"
accompanistSystemuicontroller = "0.28.0"
coroutine = "1.6.4"
coilCompose = "2.2.2"
lottieCompose = "5.2.0"
accompanistSwiperefresh = "0.28.0"
lifecycleRuntimeKtx = "2.5.1"
room = "2.4.3"
junit = "4.13.2"
truth = "1.1.3"
okhttp-mock = "4.10.0"
androidxCoreTesting = "2.1.0"
mockitoCore = "4.11.0"
mockitoInline = "4.11.0"
androidxTestingCore = "1.5.0"
androidxTestEspresso = "3.5.1"
androidxComposeUiTestJunit = "1.3.3"
androidxComposeUiTestManifest = "1.3.3"
androidDesugarJdkLibs = "1.2.2"
accompanistPager = "0.28.0"

[libraries]
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationJson" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxCompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidxCompose" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "androidxCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxCompose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-compose-foundation-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "androidxComposeFoundation" }
androidx-compose-foundation-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxComposeFoundation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidxCompose" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidxComposeMaterial" }
androidx-compose-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "androidxCompose" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidxConstraintlayoutCompose" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPagingCompose" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycleViewmodel" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigationCompose" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "daggerHilt" }
coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
room-core = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

# UnitTest
junit = { group = "junit", name = "junit", version.ref = "junit" }
coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
okhttp-mock = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp-mock" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxCoreTesting" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockitoInline" }

# AndroidTest
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestingCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestingCore" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
hilt-android-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "daggerHilt" }
androidx-compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxComposeUiTestJunit" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxComposeUiTestManifest" }

# Compiler
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHilt" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Gradle plugins
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "daggerHilt" }

accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanist-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPager" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


[bundles]
android-unittest = ["androidx-test-core",
    "androidx-test-runner",
    "androidx-test-espresso",
    "hilt-android-test",
    "androidx-compose-ui-test-junit",
    "androidx-compose-ui-test-manifest"
]
unittest = ["junit",
    "coroutine-test",
    "truth",
    "okhttp-mock",
    "androidx-core-testing",
    "mockito-core",
    "mockito-inline"
]
room = ["room-core", "room-runtime", "room-paging"]
retrofit = ["retrofit-core",
    "retrofit-kotlin-serialization",
    "kotlinx-serialization-json",
    "okhttp-core",
    "okhttp-logging"
]
hilt = ["hilt-android", "hilt-navigation-compose"]
compose = ["androidx-compose-activity",
    "androidx-compose-runtime",
    "androidx-compose-runtime-livedata",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-foundation-foundation-layout",
    "androidx-compose-foundation-foundation",
    "androidx-compose-animation",
    "androidx-compose-material",
    "androidx-compose-ui-viewbinding",
    "androidx-constraintlayout-compose",
    "androidx-paging-compose",
    "androidx-lifecycle-viewmodel",
    "androidx-navigation-compose"
]
